### ISSUE TITLE
Static providers not matching

### ISSUE THREAD

**Issue by robertspari** [jfairbank/redux-saga-test-plan#101]
I have an issue with static providers. They don't seem to be active for some reason I can't figure out.

```
import * as actionCreators from "./actionCreators";
import * as actionTypes from "./actionTypes";
import {call, put, takeLatest} from "redux-saga/effects";
import * as api from "../../services/api/albumApi";
export function* fetchAlbums() {
	try {
		yield put(actionCreators.startFetchAlbums());
		const albums = yield call(api.fetchAlbums);
		yield put(actionCreators.fetchAlbumsSuccess(albums));
	} catch (e) {
		yield put(actionCreators.fetchAlbumFailed(e));
	}
}
export default function* watchFetchAlbums() {
	yield takeLatest(actionTypes.FETCH_ALBUMS, fetchAlbums);
}
````

And I try to test it like this:
````import * as actionTypes from "./actionTypes";
import * as actionCreators from "./actionCreators";
import saga from "./sagas";
import {fetchAlbums} from './sagas';
import {call, put} from "redux-saga/effects";
import {expectSaga} from "redux-saga-test-plan";
import * as api from "../../services/api/albumApi";

describe(actionTypes.FETCH_ALBUMS, () => {
	it("fetches albums", () => {
		const fakeAlbums = [{id: 1, name: "Album 1"}, {id: 2, name: "Album 2"}];

		return expectSaga(saga)
			.provide([[call(api.fetchAlbums), fakeAlbums]])
			.put(actionCreators.startFetchAlbums())
			.put(actionCreators.fetchAlbumsSuccess(fakeAlbums))
			.dispatch(actionCreators.fetchAlbums())
			.run();
	});
	it("fetches albums traditionally", () => {
		const fakeAlbums = [{id: 1, name: "Album 1"}, {id: 2, name: "Album 2"}];
		const generator = fetchAlbums();
		expect(generator.next().value).toEqual(put(actionCreators.startFetchAlbums()));
		expect(generator.next().value).toEqual(call(api.fetchAlbums));
		expect(generator.next(fakeAlbums).value).toEqual(put(actionCreators.fetchAlbumsSuccess(fakeAlbums)));
	})
});
````

The second test (traditional one) passes but the first one doesn't because the provider doesn't match, and instead using the mock data the real API is called. If I'm reading the documentation correctly the call should be right. Version 2.4.3

**Comment by jfairbank** [comment]
Hi, @robertspari!

Thanks for opening the issue, but I'm having a hard time reproducing your example.

I copied your example and adjusted it to provide `api/actionCreators/actionTypes` and the tests passed:

<details>
<summary>Click for code</summary>

```js
import { call, put, takeLatest } from 'redux-saga/effects';
import { expectSaga } from '../src';

const actionTypes = {
  FETCH_ALBUMS: 'FETCH_ALBUMS',
  START_FETCH_ALBUMS: 'START_FETCH_ALBUMS',
  FETCH_ALBUMS_SUCCESS: 'FETCH_ALBUMS_SUCCESS',
  FETCH_ALBUM_FAILED: 'FETCH_ALBUM_FAILED',
};

const actionCreators = {
  fetchAlbums: () => ({ type: actionTypes.FETCH_ALBUMS }),
  startFetchAlbums: () => ({ type: actionTypes.START_FETCH_ALBUMS }),
  fetchAlbumsSuccess: payload => ({ payload, type: actionTypes.FETCH_ALBUMS_SUCCESS }),
  fetchAlbumFailed: () => ({ type: actionTypes.FETCH_ALBUM_FAILED }),
};

const api = {
  fetchAlbums: () => 42,
};

function* fetchAlbums() {
  try {
    yield put(actionCreators.startFetchAlbums());
    const albums = yield call(api.fetchAlbums);
    yield put(actionCreators.fetchAlbumsSuccess(albums));
  } catch (e) {
    yield put(actionCreators.fetchAlbumFailed(e));
  }
}

function* watchFetchAlbums() {
  yield takeLatest(actionTypes.FETCH_ALBUMS, fetchAlbums);
}

describe(actionTypes.FETCH_ALBUMS, () => {
  it('fetches albums', () => {
    const fakeAlbums = [
      { id: 1, name: 'Album 1' },
      { id: 2, name: 'Album 2' },
    ];

    return expectSaga(watchFetchAlbums)
      .provide([[call(api.fetchAlbums), fakeAlbums]])
      .put(actionCreators.startFetchAlbums())
      .put(actionCreators.fetchAlbumsSuccess(fakeAlbums))
      .dispatch(actionCreators.fetchAlbums())
      .run();
  });

  it('fetches albums traditionally', () => {
    const fakeAlbums = [
      { id: 1, name: 'Album 1' },
      { id: 2, name: 'Album 2' },
    ];

    const generator = fetchAlbums();

    expect(generator.next().value).toEqual(put(actionCreators.startFetchAlbums()));
    expect(generator.next().value).toEqual(call(api.fetchAlbums));
    expect(generator.next(fakeAlbums).value).toEqual(
      put(actionCreators.fetchAlbumsSuccess(fakeAlbums)),
    );
  });
});
```

</details>

---

Are you certain the code you provided matches what's in your codebase? Are you passing any arguments to the `call` that weren't provided in the code example? That would cause it not to match if you don't provide the same arguments to the matcher.

Also, what environment are you running your tests in?

Thanks!

**Comment by robertspari** [comment]
Hi,

Yes this is copy pasted right from my Codebase. If the call would have parameters wouldn't that also cause the traditional one cause to eval false?
I run this from a create-react-app boilerplate. So jasmine with Jsdom.
I'll give your code a try in my environment to see if that is the issue when I'm home tomorrow evening (Sydney time)

Thanks, Robert

**Comment by jfairbank** [comment]
Thanks for the info.

> If the call would have parameters wouldn't that also cause the traditional one cause to eval false?

Yes, that's why I wanted to check that the example and your codebase saga matched. Thanks for clarifying.

What version of Node are you using too? If you're still having trouble, then I'll need your help setting up an environment similar to yours, so we can figure out what the issue is.

Thanks!

**Comment by robertspari** [comment]
Hi,

the issue was 100% on my side. I wasn't exporting watchFetchAlbums directly but rather wrapped it in a "saga" generator function that could combine multiple functions for future use, and the call was faulty. 
Sorry to have bothered you with that.

I don't want to misuse this issue, so please feel to redirect me to another source, but I'm experiencing another "issue" when running the code I posted, or in fact your code.
I'll always receive the warning:
`[WARNING]: Saga exceeded async timeout of 250ms`because the tests take around 300ms
Could this be linked to Jasmine?

Running Node 6.10.2,
Dependencies.
````javascript
"dependencies": {
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-redux": "^5.0.4",
    "redux": "^3.6.0",
    "redux-saga": "^0.14.8"
  },
  "devDependencies": {
    "enzyme": "^2.8.2",
    "react-addons-test-utils": "^15.5.1",
    "react-scripts": "0.9.5",
    "react-test-renderer": "^15.5.4",
    "redux-saga-test-plan": "^2.4.3"
  }
````

**Comment by jfairbank** [comment]
No worries! Glad you figured it out.

The warning you're receiving comes from [here](http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/timeout.html). `expectSaga` is designed by default to time out after 250ms on sagas that take too long. That includes sagas that use `takeLatest` because it's essentially a never ending loop. You can silence the timeout by calling `run` like this:

```js
.run({ silenceTimeout: true })
```

You can also decrease the timeout length with a `time` property:

```js
.run({ silenceTimeout: true, time: 50 }) // 50ms
```

Also, if you're using Jasmine, then you'll need to use the callback feature of its tests instead of returning the result, unless Jasmine has changed since I last used it. If you specify a callback parameter, typically called `done`, for your test, then Jasmine will make your test asynchronous. You'll have to invoke the `done` callback to signal to Jasmine when your test is complete.

```js
it("fetches albums", (done) => {
  const fakeAlbums = [{id: 1, name: "Album 1"}, {id: 2, name: "Album 2"}];

  expectSaga(saga)
    .provide([[call(api.fetchAlbums), fakeAlbums]])
    .put(actionCreators.startFetchAlbums())
    .put(actionCreators.fetchAlbumsSuccess(fakeAlbums))
    .dispatch(actionCreators.fetchAlbums())
    .run()
    .then(done); // <-- pass in the `done` callback
});
```

I should add an examples page in the docs for different testing frameworks to clear up confusion in the other examples.

Does that help?

**Comment by robertspari** [comment]
Awesome, thanks so much. I really appreciate it!
