### ISSUE TITLE
Simple Example failing

### ISSUE THREAD

**Issue by kevinfez** [jfairbank/redux-saga-test-plan#106]
I copy and pasted the Simple Example from Integration section of the readme and ran jest but the test fails. 
jest: ^19.0.2
redux-saga: ^0.15.0
redux-saga-test-plan: ^2.4.4

it looks like expectSaga.put expects the output of the saga to be wrapped in an object that has a ```channel: null``` key value pair, and the action to be under an ```action``` key.
...but even wrapping the output of the saga like so:
```
yield put({channel: null, action: { type: 'RECEIVE_USER', payload: user }});
```
doesn't pass the test. I checked out some of the other issues that reference "channel" but none of them seem to address it head on or have solutions other than checking versions (so I provided those versions too)

<img width="703" alt="screen shot 2017-05-01 at 6 21 57 pm" src="https://cloud.githubusercontent.com/assets/7257376/25600804/ac36a948-2e9b-11e7-9c5a-2abc752972c2.png">

**Comment by jfairbank** [comment]
Hi, @kevinfez!

I wonder if this might be an issue with redux-saga actually. I think it could be related to https://github.com/redux-saga/redux-saga/issues/950.

I can run the simple example on redux-saga v0.15.1 fine. Can you update your redux-saga version and try again please?

Unrelated to this issue, but I'm working on adding support for new 0.15.x features per #104 too.

**Comment by kevinfez** [comment]
Thanks! after updating to redux-saga 0.15.1 both the Simple Example and my own tests are passing 🎉
