### ISSUE TITLE
Support `getContext` and `setContext`

### ISSUE THREAD

**Issue by jfairbank** [jfairbank/redux-saga-test-plan#110]
I'd like to wait until the [docs](https://github.com/redux-saga/redux-saga/issues/943) are filled in if possible before supporting these effect creators.

**Comment by denchen** [comment]
Is this still in the plan? I have a basic saga that merely does a `setContext()`, and I'd like to add a test for this. Is there currently a workaround or some way to test it now without explicit support?

**Comment by jfairbank** [comment]
Hi, @denchen. It's still the plan to add support for these. I've just been swamped the past year with a book project.

I haven't used these effects, so I'm not sure if there's a workaround for the time being. I'd gladly take some help implementing this functionality if you want.

**Comment by jfairbank** [comment]
This is finally implemented in #179 and released in v3.6.0!
