### ISSUE TITLE
Stubbing API calls and fetch

### ISSUE THREAD

**Issue by abelta** [jfairbank/redux-saga-test-plan#119]
One thing I haven't been able to do successfully with this library is stubbing an API call with fetch to trigger successful or unsuccessful effects, return a specific value, etc.
Things I've tried so far are stubbing with Sinon or passing values with the `next` method but no results so far.
Can this be done with this library?

**Comment by jfairbank** [comment]
Hi, @abelta!

You should be able to do stubbing/mocking with `expectSaga` fairly easily.

```js
function* saga() {
  const user = yield call(api.fetchUser);
  yield put({ type: 'DONE', payload: user });
}

// using Jest
it('fetches the user', () => {
  const fakeUser = { id: 1, name: 'Jeremy' };

  return expectSaga(saga)
    .provide([
      [call(api.fetchUser), fakeUser] // <-- catch the call and pass in your own value
    ])
    .put({ type: 'DONE', payload: fakeUser })
    .run();
});
```

You can check out http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/mocking/static-providers.html and http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/mocking/dynamic-providers.html for some more examples.

If you're using `testSaga`, there's no reason why you can't inject fake data with the `next` method.

```js
function* saga() {
  const user = yield call(api.fetchUser);
  yield put({ type: 'DONE', payload: user });
}

it('fetches the user', () => {
  const fakeUser = { id: 1, name: 'Jeremy' };

  testSaga(saga)
    .next()
    .call(api.fetchUser);

    .next(fakeUser) // <-- pass in own value before it's consumed and then used by the put
    .put({ type: 'DONE', payload: fakeUser });
});
```

Do those examples help?

**Comment by abelta** [comment]
Hey, @jfairbank!
Thank you for your answer but it's still a little confusing to me how to use this to test a saga that might put different actions depending on the circumstances (like call succeeded or failed).
Extending on your example a saga could become something like this:
```
function* saga() {
  try {
    const user = yield call(api.fetchUser);
    yield put({ type: 'DONE', payload: user });
  } catch (er) {
    yield put({ type: 'FAILED' });
  }
}
```

Then I like to test it in two runs: one for when it's successful, one for when it fails:
```
describe('saga', () => {
  describe('call is successful', () => {
    ...
  });
  describe('call is failed', () => {
    ...
  });
});
```
But this is as far as I get since I'm not yet able to simulate different outcomes from the api call.
What's the recommended way?

**Comment by jfairbank** [comment]
You can simulate thrown errors with providers too: [link 1](http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/mocking/static-providers.html#throw-errors) and [link 2](http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/mocking/dynamic-providers.html#errors).

For your example, it could be something like this.

```js
import { throwError } from 'redux-saga-test-plan/providers';

it('succeeds', () => {
  return expectSaga(saga)
    .provide([
      [call(api.fetchUser), { name: 'Jeremy' }],
    ])
    .put({ type: 'DONE', payload: { name: 'Jeremy' } })
    .run();
});

it('fails', () => {
  return expectSaga(saga)
    .provide([
      [call(api.fetchUser), throwError(new Error('whoops'))],
    ])
    .put({ type: 'FAILED' })
    .run();
});
```

Please make sure you've read through the [docs](http://redux-saga-test-plan.jeremyfairbank.com) as they cover most use cases. If you find something lacking in the docs, though, I would greatly appreciate a PR!

**Comment by abelta** [comment]
Thank you, @jfairbank. I'll make sure to read the documentation.
