### ISSUE TITLE
Support check for actions even on exception

### ISSUE THREAD

**Issue by psachs21** [jfairbank/redux-saga-test-plan#125]
I currently have a saga similar to the following:

```js
function* sagaHelper(){
  try {
    ...
    const result = yield call(...);
    ...
  } finally {
    yield put(actions.hideSpinner());
  }
}
```

Basically, hide the spinner regardless of how it leaves the generator. This should be handled during any throw situation.

I have a test that looks something like this (in jest):

```js
test('Error path', () => {
	const provideError = ({ fn, args }, next) => {
		if (fn === http.rawGet) {
			throw new Error('ERROR');
		}
		return next();
	};

	return expectSaga(sagaHelper)
		.provide([
			{ call: provideError }
		])
		.put(actions.hideSpinner())
		.run()
		.catch(e =>
			expect(e).toEqual(new Error('ERROR'))
		);
});
```

The problem is that regardless of what actions i expect, the catch is thrown and everything looks fine. I'd like the test to actually fail if the wrong action is on the stack regardless of if there is an exception.

**Comment by GioSensation** [comment]
Is there any update on this front? @psachs21 did you manage to find a way to check the actions even when a saga throws?

**Comment by psachs21** [comment]
@GioSensation I have not, though my attention has been mostly elsewhere.

**Comment by epikhighs** [comment]
sounds like this is related to https://github.com/jfairbank/redux-saga-test-plan/issues/147

**Comment by psachs21** [comment]
@epikhighs looks about the same yes. I'll close this as #147 has more useful information than this one.
