### ISSUE TITLE
Alternative structure proposal for test code.

### ISSUE THREAD

**Issue by ctrlplusb** [jfairbank/redux-saga-test-plan#13]
Given the following saga:

``` javascript
function* mainSaga(x, y, z) {
  try {
    const action = yield take('HELLO');
    yield put({ type: 'ADD', payload: x + y });
    yield call(identity, action);
    yield fork(otherSaga, z);
  } catch (e) {
    yield put({ type: 'ERROR', payload: e });
  }
}
```

The following test applies:

``` javascript
testSaga(mainSaga, 40, 2, 20).next()
  .take('HELLO').next(action)
  .put({ type: 'ADD', payload: 42 }).next()
  .call(identity, action).next()
  .fork(otherSaga).next()
  .isDone();
```

Not saying this is strictly better, but I personally prefer this type of structure as having each `next` to the right easily indicates the return value out of the yield.  Then I can look down the left hand side to see the actual saga API hits.  Just feels a bit more concise and easier to read for me.

As a quick reference, compare the above to the version in the README:

``` javascript
saga = testSaga(mainSaga, 40, 2, 20);
saga
  .next()
  .take('HELLO')

  .next(action)
  .put({ type: 'ADD', payload: 42 })

  .next()
  .call(identity, action)

  .next()
  .fork(otherSaga)

  .next()
  .isDone();
```

---

Absolutely loving this library man, thanks!

**Comment by jfairbank** [comment]
Hi, @ctrlplusb!

Thanks for the suggestion. While I admit the current style is rather long and verbose, I've personally found it to be easier to keep track of each step in the saga as well as refactoring the test plan itself. I like the reasoning behind your style, but the `next`'s to the right are still throwing me off. I think this could be an interesting, more succinct approach, so I'd like to try it out a little before potentially updating the README. Thanks again!

**Comment by jfairbank** [comment]
Hey again @ctrlplusb.

I've thought this over some. I appreciate your suggestion, but I'm not particularly keen on the style personally, so I'm going to leave the code samples as is. Thanks again for the suggestion!
