### ISSUE TITLE
Way to pass arguments to the task

### ISSUE THREAD

**Issue by MartinCerny-awin** [jfairbank/redux-saga-test-plan#132]
I am trying to test task started by Saga helper takeLatest() and I am not able to figure out how I can pass arguments to the task.
```
export function* requestReviews({ locale }) {
  const cachedReviews = yield select(selectors.getReviews, locale);
  return cachedReviews;
}

export default function* watchRequestReviews() {
  yield takeLatest(types.REVIEWS_REQUEST, requestReviews);
}
```

I receive a SagaTestError when I try to send anything inside as it doesn't match takeLatest arguments. ` SagaTestError: 
    Assertion 2 failed: actual takeLatest did not take a pattern`

This is how my test looks like
```
it('should get reviews', () => {
  const data = {
    locale: 'en',
  };

  return testSaga(watchRequestReviews)
    .next()
    .takeLatest(types.REVIEWS_REQUEST, requestReviews(), data)
    .run();
});
```

**Comment by jfairbank** [comment]
Hi, @MartinCerny-awin!

Please double check the [Saga Helpers](http://redux-saga-test-plan.jeremyfairbank.com/unit-testing/saga-helpers.html) page in the documentation for `testSaga`.

How you write this test largely depends on which `takeLatest` you're using.

If you're using the `takeLatest` _effect_ from `redux-saga/effects`, then you'll want your test to look like this:

```js
import { select, takeLatest } from 'redux-saga/effects';
import { testSaga } from 'redux-saga-test-plan';

function* requestReviews({ locale }) {
  const cachedReviews = yield select(selectors.getReviews, locale);
  return cachedReviews;
}

function* watchRequestReviews() {
  yield takeLatest(types.REVIEWS_REQUEST, requestReviews);
}

it('should get reviews', () => {
  testSaga(watchRequestReviews)
    .next()
    .takeLatestEffect(types.REVIEWS_REQUEST, requestReviews);
});
```

Notice that you need to use the `takeLatestEffect` assertion. If you're using the `takeLatest` _helper_ from `redux-saga`, then I advise updating your import to what I have above.

I.e. change this:

```js
import { takeLatest } from 'redux-saga';
```

To this:

```js
import { takeLatest } from 'redux-saga/effects';
```

---

More importantly, I think you might be accidentally confusing `testSaga` and `expectSaga`. I noticed that you're trying to call `.run()` on the `testSaga` chain. That method is only for `expectSaga` chains.

Also, `testSaga` is strictly for unit testing and in your case **will not** run `requestReviews`. `testSaga` will only ensure that `takeLatest` was yielded with `requestReviews` as an argument.

If you truly want to run `requestReviews`, then you'll want to write a test with `expectSaga` like this:

```js
import { put, select, takeLatest } from 'redux-saga/effects';
import { expectSaga } from 'redux-saga-test-plan';

function* requestReviews({ locale }) {
  const cachedReviews = yield select(selectors.getReviews, locale);
  yield put({ type: types.RECEIVE_REVIEWS, payload: cachedReviews });
}

function* watchRequestReviews() {
  yield takeLatest(types.REVIEWS_REQUEST, requestReviews);
}

it('should get reviews', () => {
  const locale = 'en';

  return expectSaga(watchRequestReviews)
    .provide([
      [select(selectors.getReviews, locale), '5 stars!'],
    ])
    .dispatch({ type: types.REVIEWS_REQUEST, locale })
    .put({ type: types.RECEIVE_REVIEWS, payload: '5 stars!' })
    .silentRun();
});
```

Notice that I provide some mock data for `select` with `.provide`.

Then, I `dispatch` the `REVIEWS_REQUEST` action with the `locale`, and `put` a new `RECEIVE_REVIEWS` type with a fake review `payload` inside `requestReviews`.

Finally, I can assert that `requestReview` did in fact run by checking for its `put` in the `expectSaga` chain.

---

Let me know if that makes sense. Also, please read through the docs and make sure you see the difference between `testSaga` and `expectSaga`. `testSaga` won't run forked sagas, but `expectSaga` will.
