### ISSUE TITLE
Advice on asserting all effect on unit test.

### ISSUE THREAD

**Issue by dcarrot2** [jfairbank/redux-saga-test-plan#135]
Thanks for the great lib!

I'm looking to assert a saga that yields an all effect.  I read through the unit test section of the docs but couldn't seem to find how to do this. I can see that in the output, it is receiving the array of effects I'm trying to shoot off in parallel.

Here's my saga:

```javascript
export function* retryFailedUploads() {
  const [failedDelivery, failedInventory] = yield all([
    call(getUploadFailureDelivery, { username, siteNo }),
    call(getUploadFailureInventory, { username, siteNo })
  ]);
...
```

and my test:

```javascript
it('fails upload inventory', () => {
    const saga = testSaga(retryFailedUploads);
    saga

      .next()
      .select(getUserCredentials)

      .next({ username: 'foo' })
      .select(getSiteNumber)

      .next(3)
      .all([]);
  });
```

and my output of my test
![image](https://user-images.githubusercontent.com/6015914/28441244-accdc0ba-6d5e-11e7-94d5-b6528e4c1435.png)

Any advice on how to do this?

**Comment by erikvold** [comment]
Your test should just be:

```
it('fails upload inventory', () => {
    const saga = testSaga(retryFailedUploads);
    saga
      .next()
      .all(all([
        call(getUploadFailureDelivery, { username, siteNo }),
        call(getUploadFailureInventory, { username, siteNo })
      ]));
  });

```

**Comment by dcarrot2** [comment]
@erikvold Thanks that did the trick! 

```javascript
all([
  call(getUploadFailureDelivery, { username, siteNo }),
  call(getUploadFailureInventory, { username, siteNo })
])
```

And oops, I messed up the test paste, hence why you saw the multiple `next's` before the `all`.
