### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by ifiokjr** [jfairbank/redux-saga-test-plan#150]
I'm looking to use this library within our TypeScript project, and type definitions would be super useful. Is anything like this on the cards? If not, I'd be willing to submit a PR.

**Comment by jfairbank** [comment]
Hi @ifiokjr.

Sorry for letting this issue slip under my radar. It looks like someone has opened up a PR for some typescript definitions already #156. I've never used typescript seriously, so if you'd like to still help out, I could use another typescript dev's eyes on that PR. Thanks!
