### ISSUE TITLE
Compatibility with redux-saga 0.16.0?

### ISSUE THREAD

**Issue by tmartensen** [jfairbank/redux-saga-test-plan#153]
I noticed that after updating `redux-saga` to `0.16.0`, that I now get a dependency warning:
```
redux-saga-test-plan@3.2.0 requires a peer of redux-saga@>= 0.15.0 < 0.16.0 but none is installed. You must install peer dependencies yourself.
```
Is this a matter of just updating the `peerDependencies` block in `package.json`, or is there a breaking change?

**Comment by jfairbank** [comment]
Sorry, this one slipped under my radar. No big or breaking changes in redux-saga, so I bumped the `peerDependencies` and added support in v3.3.0.

**Comment by maracuja-juice** [comment]
@jfairbank You should also update the readme though.
