### ISSUE TITLE
withReducer doesn't work correctly

### ISSUE THREAD

**Issue by alex-zh** [jfairbank/redux-saga-test-plan#157]
I use expectSaga with reducer, for some reason 'yield put' from saga doesn't update state via reducer, so the following code breaks. Update of state will be invoked later.

Test code to reproduce the problem:

function* mySaga() {
    yield takeLatest('MY_START_ACTION_TYPE', innerSaga);
  }

  function* innerSaga() {
    yield put({type: 'MY_CHANGE_DATA_TYPE', value: 'new value'});
    const result = yield select(state => state.data);
    if (result !== 'new value') { //here we have old 'value'
      throw new Error(); //we got an error, state will be updated later for some reason!!! 
    }
  }

  const myReducer = (state, action) => {
    switch (action.type) {
      case 'MY_CHANGE_DATA_TYPE':
        return {
          ...state,
          data: action.value,
        };
      default:
        return state;
    }
  };

  it('my test', async () => {
    const myState = {data: 'value'};

    await expectSaga(mySaga)
      .withReducer(myReducer, myState)
      .dispatch({type: 'MY_START_ACTION_TYPE'})
      .silentRun();
  });

**Comment by jfairbank** [comment]
Hi, @alex-zh! There is actually a fix for this in #154, which I published in v3.3.1 just now.

Try out v3.3.1 to see if it fixes your problem.

**Comment by alex-zh** [comment]
Hi jfairbank! Great news, will try! 
Thank you!
