### ISSUE TITLE
Remove redundant dependency `gitbook-plugin-github`

### ISSUE THREAD

**Issue by b1f6c1c4** [jfairbank/redux-saga-test-plan#163]
The (non-dev) dependency `gitbook-plugin-github` is not used by any code.
Besides, it generates the following warning during `yarn`:
```
warning gitbook-plugin-advanced-emoji@0.2.2: The engine "gitbook" appears to be invalid.
warning gitbook-plugin-github@2.0.0: The engine "gitbook" appears to be invalid.
```
It's unnecessary for other packages, which depends on `redux-saga-test`, to rebuild your docs with `gitbook`. Thus, it's advisable to remove the dependency, possibly by reverting [this commit](https://github.com/jfairbank/redux-saga-test-plan/commit/db06f8326220f9ee473da2a6df57205ea89ce63f).

**Comment by jfairbank** [comment]
Fixed in v3.4.0.
