### ISSUE TITLE
How to test 'select' with multiple reducers?

### ISSUE THREAD

**Issue by realmunk** [jfairbank/redux-saga-test-plan#170]
I am testing a reducer, which is a part of multiple reducers that are combined with combineReducers.

```
export default combineReducers({
  horses,
  cats,
  babies,
  users
});

```

I am writing a test to validate that on 'ADD_USER' works as intended

```
function* addUser(action) {

  let user = action.data;

  try {

    yield put({ type: 'ADD_USER_REQUESTED' });

    if (!user || !user.state || !user.profile_picture_url || !user.id || !user.username) {
      throw new Error('addUser called without appropriate data');
    }

    let current_users = yield select(store => store.users.data);

    const EXISTS = current_users.find((user) => {
      return user.id === action.data.id;
    });

    if (EXISTS) {
      return yield put({ type: 'UPDATE_USER', data: user });
    }

    yield put({ type: 'ADD_USER_SUCCEEDED', data: user });

  } catch (error) {

    yield put({
      type: 'ADD_USER_ERROR',
      data: {
        error: error,
        severity: 'high',
        reload: false
      }
    });

  }
}
```

The test is: 

```
it('should be able to add and preload a new user', async () => {

    let newUser = mock.user();

    const initialState = {
      data: []
    };

    const {storeState} = await expectSaga(userSaga)
      .withReducer(usersReducer, initialState)
      .put({type: 'ADD_USER_REQUESTED' })
      .put.actionType('ADD_USER_SUCCEEDED')
      .dispatch({type: 'ADD_USER', data: newUser })
      .run();

    expect(storeState.data.length).toEqual(1);
  });
```

However, this gives me the error:

```
SagaTestError:
    put expectation unmet:

    Expected
    --------
    { action: { type: 'ADD_USER_SUCCEEDED' } }

    Actual:
    ------
    1. { channel: null,
      action:
       { type: 'ADD_USER_ERROR',
         data:
          { error: [TypeError: Cannot read property 'data' of undefined],
            severity: 'high',
            reload: false } } }

```

How can I test a nested reducer with a saga that has a select effect?

**Comment by epikhighs** [comment]
I think you need to pass in the initial argument to your userSaga.  The error seems like it's coming from the first statement of addUser saga

```
 const {storeState} = await expectSaga(userSaga, {data: 'something'})
```

**Comment by jfairbank** [comment]
@epikhighs is right. You need to pass in your action as an argument since it's a parameter for your saga.

@realmunk Can you confirm this fixes your issue?

**Comment by realmunk** [comment]
Ah, that most definitely could've been the issue. But – the function in question is triggered by a ADD_USER event:

```
  yield takeEvery('ADD_USER', addUser);
```

Adding this action as an argument does not work to resolve the error. Do you have any other ideas?

**Comment by epikhighs** [comment]
Oh, I see what you're saying @realmunk .  I haven't tried to test sagas in the way you're trying to test them.  Basically, it seems you're trying to test a child saga from the userSaga.

I'd recommend testing the addUser saga directly as originally suggested.  But I tried out a small test snippet and it seems child saga testing should work (see snippet below).  So that leads me to think that maybe your `let newUser = mock.user();` might be the issue.  Are you sure newUser is an object?

```
  describe(`childSaga`, () => {
    it(`should`, () => {
      return expectSaga(parentSaga)
        .dispatch({ type: 'ADD_USER', data: { foo: 1 } })
        .run();
    });
  });

const childSaga = function* (action) {
  yield 1;
  console.log(action.data);
};

const parentSaga = function* () {
  yield takeEvery('ADD_USER', childSaga);
};

```

**Comment by realmunk** [comment]
Thanks @epikhighs, to solve the error I had to mock the select function. Should've thought of that sooner, but I weren't able to do it without adopting the `selector` pattern.

```
const {storeState} = await expectSaga(userSaga)
      .provide([
        [select(getUsers), []]
      ])
      .withReducer(usersReducer, initialState)
      .put({type: 'ADD_USER_REQUESTED' })
      .put.actionType('ADD_USER_SUCCEEDED')
      .dispatch({type: 'ADD_USER', data: newUser })
      .run();
```

Note to self: keep all select functions in a selectors file. For easier refactoring and testability.
