### ISSUE TITLE
[Enhancement] Provide helper for creating a combined reducer given an initial state for selectors and tested reducers.

### ISSUE THREAD

**Issue by ramblingenzyme** [jfairbank/redux-saga-test-plan#173]
It would be great to include a helper that takes an initial state, reducers you want to test and creates a combined reducer.

Such as `createTestReducer(reducers, state)`.

Am happy to create a PR for it.

**Comment by jfairbank** [comment]
Hi, @ramblingenzyme.

Would this be the same as `combineReducers` from redux? I don't see any benefit of providing a helper function when you could use `combineReducers` instead. Maybe I'm misunderstanding what you mean.

**Comment by ramblingenzyme** [comment]
It would involve using `combineReducers` yes, but what I mean is a helper
function to create a combined reducer based on the reducers targeted by a
test as well as just create dummy reducers for properties in the store that
are only selected. So you don't have to import the combined reducer used in
the actual codebase, but also don't have to pull in the reducers for parts
of state that are only selected in the saga.
