### ISSUE TITLE
Use deep equality for returned value from generator

### ISSUE THREAD

**Issue by ekimlinger** [jfairbank/redux-saga-test-plan#175]
Ultimately, what I am trying to do is retrieve the returned value from a redux-saga, while still being able to mock the selectors that are happening within.

That being said I have tried two different ways to accomplish this, however I have had no luck. 

### Method 1:
```
testSaga(makeNewFavoritesList, fakeAction)
                .next()
                .next(Immutable.List([]))
                .next(Immutable.Map(fakeOrder))
                .returns(Immutable.List([fakeOrder])) //redux-saga-test-plan does not support deep equality
                .isDone();
```
This method does not allow for deep equality so the two immutable lists are never going to be the same. 

### Method 2:
The other method I have tried is using `expectSaga` and trying to run() and `.then(` from there in attempts to get the value, however I am prompted with an error from the rejected promise: 
`TypeError: Cannot read property 'apply' of undefined`
Here is the code: 
```
...within async test function...
const { returnValue } = await expectSaga(makeNewFavoritesList)
                .provide([
                    [
                        select(readEmployeeJobOrderFavoritesList),
                        Immutable.List(),
                    ],
                    [select(readJobBoardOrder), Immutable.Map(fakeOrder)],
                ])
                .run()
                .then();
            expect(returnValue).toEqual('something');
```

Somebody help!

**Comment by epikhighs** [comment]
What's your implementation for `makeNewFavoritesList` ?

**Comment by ekimlinger** [comment]
```
export function* makeNewFavoritesList(action) {
    const oldFavoritesList = yield select(readFavoritesList);
    if (action.favorite) {
        const order = yield select(readOrder, action.orderId);
        const orderWithPropertiesToSave = _.pick(
            order && order.toJS(),
            ['<somePropertiesToPickOut>']
        );
        // Add the new one
        return oldFavoritesList.push(orderWithPropertiesToSave);
    }
    // Remove any occurrences of the id
    return oldFavoritesList.filter(val => val.orderId !== action.orderId);
}
```
The `fakeAction` in the case of the test above would have a valid orderId, and `favorite: true`

**Comment by epikhighs** [comment]
I haven't used testSaga, but with your method # 2 you should probably pass in the fakeAction

```
const { returnValue } = await expectSaga(makeNewFavoritesList, fakeAction)
```

Also, you'd also need to add providers for  the `readFavoritesList` and `readOrder` selector.

**Comment by ekimlinger** [comment]
Ah, my apologies. The code was changed since my first comment. `readFavoritesList` is the same as `readEmployeeJobOrderFavoritesList`, also `readOrder` = `readJobBoardOrder`.
However, that is somewhat besides the point. redux-saga-test-plan doesn't provide a way to compare deep values in the way that `toMatchObject` works in jest, thus preventing two immutable objects to be deeply equal to each other.

**Comment by epikhighs** [comment]
Hmm.  I was trying to solve the error you mentioned.  But if you're no longer encountering an error, then you could use a separate assertion library like chai.js.  It has support for .include() partial matching deeply nested objects or deepEqual checking (http://chaijs.com/api/assert/#method_deepequal).

I'd imagine providing yet another implementation of deep equality check would be outside the scope of this project IMHO.

**Comment by ekimlinger** [comment]
Yeah, sorry. I believe I tried it with the action in the expectSaga using method #2 however that didn't work either. 
I ended up just running the saga on it's own without the library in order to generate the values necessary to test. 
Thank you @epikhighs for trying to help out!
