### ISSUE TITLE
Comparison of the generated selection functions

### ISSUE THREAD

**Issue by pavelMojo** [jfairbank/redux-saga-test-plan#177]
**Hi**, i'm having some problems with comparison of the select functions:
This is begining of my saga:
```
    export function* mySaga() {
        const { data } = yield select(componentSelectors.getComponent(componentId))
        
        /** some logick */
    }
```
and a test for her:
```
    it('Testing mySaga', () => {
        const componentId = 1;
        testSaga(mySaga)
            .next()
            .select(componentSelectors.getComponent(componentId))

            /** test continuation */
    });
```

When I run the test, I get an error: _"select effects do not match"_

```
    Expected
    --------
    { selector: [Function: bound ], args: [] }

    Actual
    ------
    { selector: [Function: bound ], args: [] }
```

And so it happens to all tests, where i'm using generated selector getComponent and other like him: 

```
    const getComponents = state => state["components"];
    const getComponent = id => state => {
        const { [id]: component } = getComponents(state);
        return component;
    };
    export const componentSelectors= {
        getComponents,
        getComponent
        }
    }
```
Can I somehow use your library to compare the generated functions?

**Comment by pavelMojo** [comment]
The problem is that with each access a new function was generated. 
I was helped by the use [reselect](https://github.com/reactjs/reselect) library. After wrapping my selectors with reselect, I can get the same result (the first generated function), until the call conditions change and select effects now will match.

**Comment by epikhighs** [comment]
I'd probably mock the getComponent selector using something like sinon.js.  This way you can get the same function reference.

**Comment by jfairbank** [comment]
@pavelMojo Since you're dynamically creating the selector function, you won't be able to compare it as normal. You can mock the selector function like @epikhighs mentions, or you could switch to `expectSaga` and test your selector against your reducer/state (http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/state.html).

```js
it('Testing mySaga', () => {
  return expectSaga(mySaga)
    .withReducer(reducer)
    // whatever assertions you need
    .run()
});
```

You could also use dynamic providers (http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/mocking/dynamic-providers.html) with `expectSaga` to return fake data.

```js
it('Testing mySaga', () => {
  return expectSaga(mySaga)
    .provide({
      select() {
        return { data: ... }
      }
    })
    // whatever assertions you need
    .run()
});
```

**Comment by arnaudambro** [comment]
@pavel-rakhmanov I encountered the same issue, this is how I solved it:

```js
import componentSelectors from '../selectors'
jest('../selectors')

it('Testing mySaga', () => {
  beforeAll(() => {
    const noOp = () => {}
    componentSelectors.getComponent.mockImplementation(() => noOp)
  })
  const componentId = 1;
  testSaga(mySaga)
      .next()
      .select(componentSelectors.getComponent(componentId))
      .next(/* component */)
      .isDone()
});
```

**Comment by cdow** [comment]
Another option that doesn't involve any mocking is you can wrap the creation of your generated function with a `call`.  This results in the original function looking like this:
```js
export function* mySaga() {
  const componentSelector = yield call(componentSelectors.getComponent, componentId);
  const { data } = yield select(componentSelector);
        
  /** some logic */
}
```
This can then be tested with:
```js
it('Testing mySaga', () => {
  const componentId = 1;
  const componentSelector = () => {};
  
  testSaga(mySaga)
    .next()
    .call(componentSelectors.getComponent, componentId)
    .next(componentSelector)
    .select(componentSelector)

    /** test continuation */
});
```

**Comment by AshifMohammad** [comment]
const mockState = { rick:"Genius", Morty:"dumbAsss"}

expectSaga(yourCoolSaga)
      .provide({
        select({ selector }, next) {
          if (selector) {
            return mockState;
          }
          return next();
        }
      })
    // some assertion here
      .put(actions.updateRickMortyPowers(mockState))
      .silentRun();
