### ISSUE TITLE
API reference

### ISSUE THREAD

**Issue by jacobworrel** [jfairbank/redux-saga-test-plan#181]
Great job on the library and providing clear documentation. It would be really helpful though to have an API reference to quickly reference methods, arguments and how they can be used.

Cheers!

**Comment by jfairbank** [comment]
Thanks @jacobworrel!

This is something that has been on my radar. I have an older issue to add an API reference: #93. My time is really divided at the moment, so I haven't had time to put this together. I'll always gladly accept PRs, though, if someone could help out.
