### ISSUE TITLE
Support redux-saga v0.16

### ISSUE THREAD

**Issue by lee-alexander** [jfairbank/redux-saga-test-plan#187]
Hey! The docs call out that only v0.15 of redux-saga is currently supported. Are there any breaking changes in v0.16 that would cause this library to not work correctly? If so, is there a plan to upgrade this library to support v0.16 moving forward?

**Comment by thibautguedou3** [comment]
It seems to be compatible since redux-saga-test-plan v3.3.0 
https://github.com/jfairbank/redux-saga-test-plan/commit/10860591d06284fb7eb7d85315de3681bc464722

**Comment by jfairbank** [comment]
Hi @lee-alexander.

😱I never updated the docs or README to state support for 0.16. But yes, redux-saga-test-plan has supported 0.16 for a while now. Sorry for the confusion. Would you mind opening a PR to update the docs?

**Comment by AugustoAleGon** [comment]
PR opened. feel free to read it. @jfairbank
