### ISSUE TITLE
Tests exceeding timeout with takeLatest

### ISSUE THREAD

**Issue by sethen** [jfairbank/redux-saga-test-plan#208]
I am trying to implement the redux-saga-test-plain into my project, but every test I make just gives me an error message of `[WARNING]: Saga exceeded async timeout of 250ms` -- I am not sure how to fix this.  I've followed the instructions in the directions and feel like I am doing everything right.

Here is my test:

```
import { expectSaga } from 'redux-saga-test-plan';
import { requestAuth0Token } from '../../src/sagas/auth0';

describe('sagas/auth0', () => {
	describe('requestAuth0Token', () => {
		it('test', () => {
			return expectSaga(requestAuth0Token)
				.run();
		});
	});
});
```

Here is my saga:

```
import Auth0Actions from '../actions/Auth0';
import Auth0API from '../data/Auth0';
import { call, put, takeLatest } from 'redux-saga/effects';
import { setCookieAccessToken } from '../lib/users';

export function* receiveAuth0Token() {
	const { data } = yield call(Auth0API.postAuth0Token);

	try {
		const hasAccessTokenKeys = data !== undefined && data.hasOwnProperty('access_token');

		if (hasAccessTokenKeys) {
			setCookieAccessToken(data.access_token);

			yield put(Auth0Actions.receiveAuth0AccessToken());
		}
		else {
			throw new Error('no access token available');
		}
	}
	catch (e) {
		yield put(Auth0Actions.failedAuth0AccessToken());
	}
}

export function* requestAuth0Token() {
	const { type } = Auth0Actions.requestAuth0AccessToken();

	yield takeLatest(type, receiveAuth0Token);
}
```

Does `takeLatest` not work with `expectSaga` or something?

**Comment by sethen** [comment]
I actually found something here that explains this a little bit better: https://survivejs.com/blog/redux-saga-test-plan-interview/ -- are timeouts expected here when using something like `takeLatest`?

**Comment by nkalinov** [comment]
http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/timeout.html

**Comment by sethen** [comment]
Yeah I did read that.  I guess the question I was curious about is it timeouts are necessary for the tests to work?  From my research it sounds like this expected behavior.  I was under the impression it wasn’t.
