### ISSUE TITLE
delay broken on v4.0.0-beta.1

### ISSUE THREAD

**Issue by StefanoDeVuono** [jfairbank/redux-saga-test-plan#227]
Running the delay assertion on `testSaga` raises a `TypeError: Cannot read property 'apply' of undefined`

```javascript
const TIMEOUT = 15 * 1000 * 60;
const thing = testSaga(saga)
  .next()
  .call(api.refresh, { grantType: "refresh_token" })
  .next(response)
  .put(refreshCookieSuccess(response.data))
  .next()
  .delay()
```

Apparently `createEffectTester` in `node_modules/redux-saga-test-plan/lib/testSaga/index.js:55` is not getting passed an `effect` parameter. This is because the `delay` is not a key on `reduxSaga.effects` but rather directly on `reduxSaga` itself.

Moreover I tried monkey patching this in by adding:
```javascript
  function createEffectTesterFromEffects(name, key) {
    _reduxSaga.effects.delay = _reduxSaga.delay
    return createEffectTester(name, key, _reduxSaga.effects[name]);
  }
```
to `node_modules/redux-saga-test-plan/lib/testSaga/index.js68` myself but I got an error:

```javascript
   SagaTestError:
    Assertion 3 failed: expected delay effect, but the saga yielded a different effect

    Expected
    --------
    { '@@redux-saga/CANCEL_PROMISE': [Function] }

    Actual
    ------
    { '@@redux-saga/CANCEL_PROMISE': [Function] }
```

**Comment by prijuly2000** [comment]
i have a simple saga 
```
export default function* rootSaga() {
    yield takeLatest(INIT_NEWS_ITEMS, init);
}
```
test
```
testSaga(sagas.rootSaga)
            .next()
            .takeLatest(initNews())
            .next()
            .isDone();
```
throws
```
 TypeError: Cannot read property 'apply' of undefined
```
I think the error is thrown by `testSaga` itself.
Having same issue

**Comment by jp928** [comment]
This suppose to be fixed in beta.2.
