### ISSUE TITLE
Help: When the redux-saga version is greater than v1.0.0-beta.1, I get an error.

### ISSUE THREAD

**Issue by olabala** [jfairbank/redux-saga-test-plan#235]
The following is the error message:
![image](https://user-images.githubusercontent.com/20949823/48482377-7ea90f00-e84b-11e8-9cb1-9feb1b82be11.png)

but when I changed the redux-saga version back to v1.0.0-beta.1 it was normal, so I think it may be caused by redux-saga-test-plan not yet supported the new version.

Begging to support the new version!!!

**Comment by stefanfrede** [comment]
With Redux-Saga v1.0.0-rc.0 live for 2 weeks now, which is most likely the only release candidate version before v1.0.0, it would be nice if redux-saga-test-plan could be updated to work with this version.

**Comment by VincentLanglet** [comment]
They need maintainer for that https://github.com/jfairbank/redux-saga-test-plan/issues/134

**Comment by jp928** [comment]
@olabala
I made a fork which working with 1.0.0z please test.
https://github.com/jp928/redux-saga-test-plan
