### ISSUE TITLE
TypeError with put effect when use channel

### ISSUE THREAD

**Issue by iamchanii** [jfairbank/redux-saga-test-plan#252]
I'm using channel and this is a snippet of my code:

```ts
function* handleHttpRequestAction(action: ReturnType<typeof HttpRequestActions.request>) {
    const { payload: [url, options] } = action;
    const chan = options.channel;

    try {
        const result = yield call(HttpClient, url, options);

        if (chan) {
            yield put(chan, HttpRequestActions.success(result));
        } else {
            console.warn('Unhandled HttpRequestSuccessAction:', result, { url, options });
        }
        // ...
```

and I wrote test code. but I faced typing error.

```ts
return expectSaga(HttpRequestSaga)
    .dispatch(action)
    .call(HttpClient, url, httpClientOptions)
//  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    .put(chan, HttpRequestActions.success(result))
    .silentRun();
```
```
Error:(38, 16) TS2554: Expected 1 arguments, but got 2.
```

currently, I'm use this with ts-ignore. it works.
```ts
// @ts-ignore
return expectSaga(HttpRequestSaga)
    .dispatch(action)
    .call(HttpClient, url, httpClientOptions)
    .put(chan, HttpRequestActions.success(result))
    .silentRun();
```

thanks for your works. I felt good saga test experience with this library.

**Comment by dcbrwn** [comment]
@jp928 maybe you can help? I have the same issue and it doesn't look like there is any workaround. Maybe you can guide where in codebase this can and should be fixed? I'd be more than happy to make a PR for this

**Comment by jp928** [comment]
@dcbrwn
Could you advise the version you are working with?
on the latest 4.0.0-beta.2 in the effects.d.ts
we define the `call` like

```
call(fn: Function, ...args: any[]): R;
```

which should allow any number of paramters

**Comment by dcbrwn** [comment]
@jp928 the issue here is not with `call` but with `put` effect:
https://github.com/jfairbank/redux-saga-test-plan/blob/master/effects.d.ts#L17
https://github.com/redux-saga/redux-saga/blob/master/packages/core/src/internal/io.js#L52

`put` for channels takes 2 arguments: channel and action.

**Comment by jp928** [comment]
@dcbrwn 
Thanks for your comments. Do you mind to advise how to fix put or maybe a pull request.

**Comment by bbil** [comment]
@jp928 I've created a Pull Request that adds the necessary variant to the `index.d.ts`

**Comment by bbil** [comment]
Thanks for the merge!
