### ISSUE TITLE
`testSaga` TypeScript typings do not exist for `delay` effect

### ISSUE THREAD

**Issue by wh1t3cAt1k** [jfairbank/redux-saga-test-plan#272]
`v4.0.0-beta.2`

The code:

```
testSaga(mySaga)
    .next()
    .delay(milliseconds)
```

Does not compile in TSC but works in JS. The likely reason is that `delay` effect is missing in effects API.

**Comment by jp928** [comment]
@wh1t3cAt1k 
This should be fixed in 4.0.0-beta.3. Close this issue.
