### ISSUE TITLE
How to test a saga that will dispatch an action that in turn will do an async call if condition is met

### ISSUE THREAD

**Issue by alveshelio** [jfairbank/redux-saga-test-plan#279]
Hi guys,

I have this case. I have a panel that display some content and in this panel, I have a button "Edit", when I click "Edit" it dispatches an action "`TOGGLE_EDIT_MODE`". I have a saga that listens to this action and if `editMode` is set to `true` then it will fetch the most recent content of the detail and displays it in a `Formik` form.

I've been trying to create a test that would test this case. The "`TOGGLE_EDIT_MODE`" is dispatched with true, the action to fetch the detail is dispatched and when the server returns the detail it will dispatch an action `FETCH_DETAIL_SUCCESS` with the detail.

Here's the generator I'm trying to test:
```
export function* fetchContainerDetailOnToggleEditAsync() {
  const {
    detail: { editMode, content },
    contents: { dataSource },
  } = yield select()

  if (editMode) {
    yield put(DetailActions.fetchDetail({ detailId: content.id, detailType: dataSource }))
  }
}
```
and I have a watcher
```
function* watchFetchContainerDetailOnToggleEdit() {
  yield takeLatest(DetailActionTypes.TOGGLE_DETAIL_EDIT, fetchContainerDetailOnToggleEditAsync)
}
```

This is my test
```
test('It will toggle Edit mode and fetch the content from the container service', async () => {
    const expectedState: IDetailState & IApiFlowManager = {
      content: containerMock as Container,
      detailSaveLoader: false,
      detailSaveSuccess: false,
      editMode: false,
      apiFlowManagerDetail: undefined,
    }

    const toggleAction = {
      type: DetailActionTypes.TOGGLE_DETAIL_EDIT,
      editMode: true,
    }

    return expectSaga(fetchContainerDetailOnToggleEditAsync, toggleAction)
      .provide([[matchers.call.fn(fetchContainerDetailApi), containerMock as Container]])
      .put({ type: DetailActionTypes.FETCH_DETAIL_SUCCESS, content: containerMock as Container })
      .withReducer(rootReducer)
      .hasFinalState(expectedState)
      .run()
  })
```
This test is failing with this message:

```
SagaTestError:
    put expectation unmet:

    Expected
    --------
    { channel: null,
      action:
       { type: '@Detail FETCH_SUCCESS',
         content:
          { id: 'container-SUBJECT_SECONDARY_FEED-id-01',
            name: 'container de serie',
            type: 'SUBJECT_SECONDARY_FEED',
            status: 'PUBLISHED',
            version: 1,
            creationDate: '2019-04-14T15:44:41.055Z',
            createdBy: 'Création Statique',
            modificationDate: '2019-04-14T15:44:41.055Z',
            modifiedBy: 'Éditeur Statique',
            numberOfSlot: 1,
            slug: 'football',
            slots: [ [Object] ] } } }
```

Is there a way to debug this tests? It says `put expectation unmet`. is there a way to know what should be expected?
 
I'm out of ideas on how I could do this. I've been battling on this for a day now without much success.

I'd like to know how I can test dispatching the toggle edit action, setting editMode to true, then fetch content from the server and `put` a `FETCH_DETAIL_SUCCESS` action with the detail.

Thank you very much for your precious help

**Comment by mihaisavezi** [comment]
So from what you provided, you should ```provide``` a mock selector for your selector in ```fetchContainerDetailOnToggleEditAsync```. The mock data should contain your editMode set to true, and then your condition should be met.

**Comment by jp928** [comment]
@alveshelio 
I think @mihaisavezi had answered your question. I would like to close this but feel free to comment this if you think we need reopen this issue.
