### ISSUE TITLE
How to test saga function having multiple actions dispatched.

### ISSUE THREAD

**Issue by Yoshihide-Nishimoto** [jfairbank/redux-saga-test-plan#290]
In our redux function, multiple actions are dispatched.

like this

*saga.ts*
```
export function* testRequest(action: any) {
  try{
    yield put(Action.startLoading());
    const result = yield call(API.test)
    yield put(Action.success());
    yield put(Action.stopLoading());
  } catch() {
    yield put(Action.fail());
    yield put(Action.stopLoading());
  }
}
```

this is our test code.

*test.ts*
```
expectSaga(testRequest)
  .put(Action.success())
  .run()
```

the result is FAIL. because excepted dispatch is one, but acual is three.

```
Expected
    --------
    { '@@redux-saga/IO': true,
      combinator: false,
      type: 'PUT',
      payload:
       { channel: undefined,
         action:
          { type: '@@test/LOGIN_SUCCESSED',
            payload: undefined,
            meta: undefined,
            error: undefined } } }

    Actual:
    ------
    1. { '@@redux-saga/IO': true,
      combinator: false,
      type: 'PUT',
      payload:
       { channel: undefined,
         action:
          { type: '@@test/START_LOADING',
            payload: undefined,
            meta: undefined,
            error: undefined } } }
    2. { '@@redux-saga/IO': true,
      combinator: false,
      type: 'PUT',
      payload:
       { channel: undefined,
         action:
          { type: '@@test/LOGIN_SUCCESSED',
            payload:undefined,
            meta: undefined,
            error: undefined } } }
    3. { '@@redux-saga/IO': true,
      combinator: false,
      type: 'PUT',
      payload:
       { channel: undefined,
         action:
          { type: '@@test/STOP_LOADING',
            payload: undefined,
            meta: undefined,
            error: undefined } } }
```

Do you know how to assert this properly??

（As far as I searched, There is hardly any such implementation.... is it an anti-pattern to dispatch multiple action in saga-function?）

**Comment by jp928** [comment]
@Yoshihide-Nishimoto 
This is a very good thinking, IMP. The testing result show the three actions are fired actually. I think the most concern might be “do we have to mutate the loading status from saga?” Because it absolutely fine to go through action->reducer->store which makes it looks tedious to control from saga.

**Comment by Waltari10** [comment]
I have the exact same situation. What should I do to test this? I don't quite understand why this issue was closed, as it seems to be left unanswered.

**Comment by corelema** [comment]
> I have the exact same situation. What should I do to test this? I don't quite understand why this issue was closed, as it seems to be left unanswered.

I agree, the answer is very specific to the use case presented, but there are some situations where dispatching multiple actions from one saga is definitely the right thing to do. Hence the need to be able to test it.

**Comment by trm217** [comment]
May I ask why this issue was closed?
I don't see this question answered at all.

**Comment by solalgaillard** [comment]
Testing multiple put causes absolutely no problems. Aren't you sure your issues are not linked to your expected output and your actual output actually diffing? If you look at the assertions above from @Yoshihide-Nishimoto, he asserts Action.success() first when Action.startLoading() is actually the first action dispatched. He would need to assert them in order to test the saga properly.

**Comment by hackingbeauty** [comment]
I'm trying to do the same thing...test multiple action dispatches in one saga.
Why can't this be tested?

**Comment by SveLil** [comment]
The order doesn't matter, as soon as multiple actions are dispatched, testing fails.
@jp928 Why did you close this ticket?
