### ISSUE TITLE
TypeScript - `putResolve` is not in the definition

### ISSUE THREAD

**Issue by rmevans9** [jfairbank/redux-saga-test-plan#295]
It seems in the 4.0.0 package the renamed `putResolve` method has not been updated in the TypeScript definition files. I suspect it can take on a similar definition to what the current `put` effect does while `put` should probably lose the `.resolve` definition since that is no longer valid.

**Comment by jp928** [comment]
@rmevans9 
Thanks for reporting this. We will fix it soon. In the meantime, a pull request would be welcomed as well.

**Comment by taehwanno** [comment]
This is fixed by #302 :) It will probably be available in the next release.

**Comment by jp928** [comment]
Close this because it's been solved.
