### ISSUE TITLE
"put effects do not match" error is not descriptive enough. 

### ISSUE THREAD

**Issue by vnovick** [jfairbank/redux-saga-test-plan#3]
I expect it to log the diff of what got into put in real saga and what is expected to be in there.

**Comment by jfairbank** [comment]
Thanks for submitting this issue @vnovick! This is something I definitely want to add eventually. I won't be able to get to it soon, though, so you're welcome to take a shot at a PR if you want.

**Comment by jfairbank** [comment]
@vnovick I've implemented some more helpful error messaging which you can find in the latest release v0.2.0. I'm thinking of opening a separate issue to look into showing diffs between expected and actual saga effects, but I think this will work for now. Let me know if you have any issues.
