### ISSUE TITLE
How to unit test a saga containing an infinite while loop?

### ISSUE THREAD

**Issue by blordpluto** [jfairbank/redux-saga-test-plan#311]
I want to unit test some basic saga logic that's nested in an infinite loop. I can't use `.isDone()` because it's never done listening. And without `isDone()` the `testSaga` never returns, and so the test times out and fails.

Code (simplified) like this:

```js
export function* myLoop(context) {
    let unprocessedAction;
    let state = context.state;
    let res;
    while (true) {
      try {
        switch (state) {
          case "BEGIN":
            res = yield call(handleBegin, context);
            state = res.state;
            unprocessedAction = res.unprocessedAction;
            break;
          case "MIDDLE":
            res = yield call(handleMiddle, context, unprocessedAction);
            state = res.state;
            unprocessedAction = res.unprocessedAction;
            break;
          case "END":
            res = yield call(handleEnd, context, unprocessedAction);
            state = res.state;
            unprocessedAction = res.unprocessedAction;
            break;
          default:
            break;
        }
        yield call(context.someFn, context.state, state);
        context.state = state;
      } catch (e) {
        log(e);
      }
    }
  }


test("It sure would be nice if...", () => {
    const mockContext = {
      state: "BEGIN",
      someFn: function noop() {}
    };
    const result = {
      state: "BEGIN",
      unprocessedAction: "hello"
    };

    return testSaga(myLoop, mockContext)
      .next()
      .call(handleBegin, mockContext)
      .next(result)
      .call(mockContext.someFn, mockContext.state, result.state);
});

```

Thanks in advance for any help. I am willing to tweak my source code (slightly!) to make this more testable, but would prefer to leave the source fn as is.

**Comment by vatosarmat** [comment]
Add boolean property isTest to saga context and if it is true, do only one iteration instead of infinite loop

**Comment by blordpluto** [comment]
@vatosarmat Thanks, but I would really prefer not to add code to a loop just for testing.

Turns out there is a `.finish()` method on the test which handles this perfectly. Tucked away in the "Time Travel" docs. Closing.

**Comment by sneak** [comment]
sorry for the spam but @blordpluto could you please contact me privately by any media you wish? contact info on website linked in profile.
