### ISSUE TITLE
deprecated core-js

### ISSUE THREAD

**Issue by pierroberto** [jfairbank/redux-saga-test-plan#334]
Hi Team,

Do you have any plan to upgrade core-js in the next release?
I get this warning:

> redux-saga-test-plan > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

Thanks

**Comment by jensenbox** [comment]
Is there any chance this can happen? I am using a package that is using this and is throwing a pretty scary warning.

```
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained 
and not recommended for usage due to the number of issues. 

Because of the V8 engine whims, feature detection in old core-js versions could 
cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies
to the actual version of core-js.
```

**Comment by paulcoyle** [comment]
Any movement on this?  There's a [ greenkeeper PR for this](https://github.com/jfairbank/redux-saga-test-plan/pull/261) that has been continually updating since March 19 of _2019_.  Off all the outdated dependencies, this is the one that has real downstream effects on consumers of this library.

**Comment by brumik** [comment]
Any idea when is this gonna be released? (Or at least which type of release this will be (fix|feature|breaking change)?

**Comment by jp928** [comment]
@brumik I think core-js has been removed from latest 4.0.5.

**Comment by brumik** [comment]
@jp928 When pulling 4.0.5 I am still getting these deps in node_modules/redux-saga-test-plan/package.json

```
  "dependencies": {
    "core-js": "^2.4.1",
    "fsm-iterator": "^1.1.0",
    "lodash.isequal": "^4.5.0",
    "lodash.ismatch": "^4.4.0",
    "object-assign": "^4.1.0"
  },
```

**Comment by jp928** [comment]
@brumik thanks for getting back. I will fix this soon.

**Comment by brumik** [comment]
@jp928 Are there any news on this?
