### ISSUE TITLE
Comparing expected vs actual only shows the diff a few levels deep?

### ISSUE THREAD

**Issue by jxm262** [jfairbank/redux-saga-test-plan#339]
Very similar to this PR - https://github.com/jfairbank/redux-saga-test-plan/pull/314

It seeems that the diff between the expected and actual output only goes a few levels deep (arbitrarily set at 4 from that PR, not sure if it's been changed since).  This can make it difficult to see where the actual assertion is failing.

Simple contrived example.  Note the `data` property is an array of objects - with some values inside failing the assertion, but the user can't visually see which ones.  
```
Expected
--------
{ '@@redux-saga/IO': true,
	combinator: false,
	type: 'PUT',
	payload:
	{ channel: undefined,
		action:
		{ type: 'MY_ACTION',
			payload: { data: [Object] }
		}
	}
}

Actual:
------
{ '@@redux-saga/IO': true,
	combinator: false,
	type: 'PUT',
	payload:
	{ channel: undefined,
		action:
		{ type: 'MY_ACTION',
			payload: { data: [Object] }
		}
	}
}
````

Could we consider the diff to recurse down all levels to show the true full diff?  Or at least make the depth level parameterized to accept more depth values?

Please let me know if I'm just overlooking something simple in the docs.  Or please let me know if I can make a PR with the proposed change.  

Thanks!

**Comment by rajjeet** [comment]
+1

**Comment by Vanuan** [comment]
What worked for me is using standard `expect` matchers in the `run().then(results => ...)`
It looks like that returns pretty standard objects.

**Comment by Waltari10** [comment]
I went into the file 
`/node_modules/redux-saga-test-plan/lib/expectSaga/expectations.js`

And replaced `{ depth: 3 }`, with `{ depth: 10 }` . Then I was able to run the tests and see difference down to 10 depth.

Obviously you don't want to directly modify node_modules like this, but this is probably the quickest hack to fix it.

depth 3 is compiled from the file:
`redux-saga-test-plan/src/shared/serializeEffect.js`

I guess a PR could be made where depth could be given as parameter, or I don't know why not just make it unlimited or atleast a very high number?

**Comment by jxm262** [comment]
thanks @Vanuan , didn't even think to try that.  Seems to work for now, but I'll leave this ticket open since I still think it would be a good feature to have.  Also looks like some other folks are experiencing similar issues :)

Happy to make a PR for this @jfairbank , but it looks like you have a bunch of open PR's already.  So, just let us know if you want help with any of this

**Comment by jp928** [comment]
This issue should be solved by @AdeonMaster
