### ISSUE TITLE
Error when using with Mocha

### ISSUE THREAD

**Issue by nam288** [jfairbank/redux-saga-test-plan#364]
I can not even run a sample from [docs](http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/effect-creators.html)

```javascript
import { expectSaga } from "redux-saga-test-plan";

function* saga() {
	return { hello: "world" };
}

describe("test", () => {
	it("returns a greeting", () => {
		return expectSaga(saga).returns({ hello: "world" }).run();
	});
});
```

Command: `mocha --timeout 60000 --ui bdd --sort "./lib/**/test/**/*.test.js"`

**mocha**: 7.1.2
**redux-saga-test-plan**: 4.0.0
**node**: 10.16.0

**Expected**: Pass the test
**Actual**: Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by jp928** [comment]
@nam288 
I forgot to remove package-lock.json. Is there any chance to try with yarn?

**Comment by nam288** [comment]
Sorry for my late reply. The problem is about Intellij IDE with an async test suite.
