### ISSUE TITLE
Is expectSaga() broken? Odd behavior

### ISSUE THREAD

**Issue by ehahn9** [jfairbank/redux-saga-test-plan#385]
I'm sure it is a newbie mistake, but I am surprised that the `expectSaga()` test below times out. -- advice appreciated!

```ts
import { expectSaga, testSaga } from 'redux-saga-test-plan';

function* saga() {}

// ...this passes
it('should be testable with testSaga()', () => {
  testSaga(saga).next().isDone();
});

// ...this times out
it('should be testable with expectSaga()', () => {
  return expectSaga(saga).run();
});
```

* redux-saga-test-plan@4.0.4
* redux-saga@1.1.3
* react 17
* jest@27.5.1
* typescript@4.6.3

**Comment by nicholaschedid** [comment]
@ehahn9 I'm having the same issue. Did you found a solution?

**Comment by ehahn9** [comment]
@nicholaschedid no, never did but we ended up dropping react-saga from the project so I didn't continue to investigate.

**Comment by MaxToyberman** [comment]
You can use this patch to fix the issue.

[redux-saga-test-plan+4.0.6.patch](https://github.com/jfairbank/redux-saga-test-plan/files/14672272/redux-saga-test-plan%2B4.0.6.patch)

In general jest 27 had this [BREAKING CHANGE] Remove Node globals setImmediate and clearImmediate (https://github.com/facebook/jest/pull/11222)
