### ISSUE TITLE
Getting put effects do not match:

### ISSUE THREAD

**Issue by timothyjlaurent** [jfairbank/redux-saga-test-plan#4]
I am using redux-saga 0.11.0. I pass in the value to the testSaga that gets passed into the real value but it is throwing an error 

I traced this to the lodash isEqual function call:

here is my `value`:
![image](https://cloud.githubusercontent.com/assets/2000204/17306203/a431a3e0-57e3-11e6-9843-872e7332176b.png)

![image](https://cloud.githubusercontent.com/assets/2000204/17306215/ac2d742a-57e3-11e6-8103-29a41c61769e.png)

Notice the additional channel key here ^^ that is causing the error to be thrown

I will try downgrading redux-saga to 0.10.x and see if that helps.

**Comment by timothyjlaurent** [comment]
Downgrading doesn't help

**Comment by jfairbank** [comment]
Hi, @timothyjlaurent!

I can't reproduce this particular issue at the moment. If you're using `put` in your saga and calling the `put` method from the `testSaga` object, then they should be producing the same effect. The `put` test method delegates to Redux Saga's `put` effect. Are you able to share your actual saga generator code or provide a failing test case or JSFiddle showing the error?

**Comment by timothyjlaurent** [comment]
I'm going to close this as I don't have a test case anymore and I'm not using the test plan.
