### ISSUE TITLE
Support redux-saga 0.14.x

### ISSUE THREAD

**Issue by andys8** [jfairbank/redux-saga-test-plan#47]
Redux saga is release in [version `0.14.0` and `0.14.1`](https://github.com/redux-saga/redux-saga/releases). The peer dependencies are not mentioning the new versions. Once they're with `redux-saga-test-plan` tested, they should be allowed.

**Comment by jfairbank** [comment]
Thanks for opening this. I hadn't had a chance to add 0.14 support over the holidays. I can't just bump the peerDependencies, though. 0.14 added effect creators for `takeEvery` and the other saga helpers that redux-saga-test-plan needs to support. I'll likely drop support for older versions of redux-saga when I do this per #36 too.

**Comment by jfairbank** [comment]
@andys8 redux-saga-test-plan v2 is out with support for redux-saga 0.14.x. Thanks again!

**Comment by andys8** [comment]
Awesome, good job!
