### ISSUE TITLE
Need help setting up async test with expectSaga

### ISSUE THREAD

**Issue by mpmlj** [jfairbank/redux-saga-test-plan#54]
Hi,

I would really appreciate if you could guide me through testing the following saga!

Details:
- This is a saga for submitting a form with just one value, which is accumulated in a store: "initialState" const, "msg" var.
- When generating a POST call, i'm:
-- Taking "msg" value from the store via getMsg select and use it in the POST call body.
-- Loading a token from local storage and use in a header, however I have a feeling we can just skip this from the tests.

My problem: the test returns failed connection whatever I do (if I implement a test for failure - it will work as expected):

```Javascript
SagaTestError:
    put expectation unmet:

    Expected
    --------
    { channel: null, action: { type: 'fb/post/POST_SUCCEEDED' } }

    Actual:
    ------
    1. { channel: null,
      action:
       { type: 'fb/post/POST_FAILED',
         errorMessage: 'Connection error' } }


      at new SagaTestError (node_modules/redux-saga-test-plan/lib/SagaTestError.js:17:57)
      at node_modules/redux-saga-test-plan/lib/expectSaga.js:347:15
      at Array.forEach (native)
      at checkExpectations (node_modules/redux-saga-test-plan/lib/expectSaga.js:333:18)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

I'm not yielding the axios call explicitly following these instructions: http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/, so  I suspect I'm not correctly setting the test properly.

Any insights are greatly appreciated!

TEST:
```Javascript
import nock from 'nock';
import { expectSaga } from 'redux-saga-test-plan';
import axios from 'axios';
import httpAdapter from 'axios/lib/adapters/http'
import { POST_SUCCEEDED } from '../actions/types';
import reducers from '../reducers';

const initialState = {
  wallpost: {
    busy: true,
    error: false,
    msg: 'foo',
  },
};

// Workaround for axios <-> sagas compat: https://github.com/node-nock/nock/issues/699
const host = 'http://localhost';
axios.defaults.host = host;
axios.defaults.adapter = httpAdapter;

describe('wallpostform Saga', () => {

  it('on success should yield POST_SUCCEEDED', () => {

    nock('http://localhost:9090')
      .post('/v0.1/posts/post', {
        msg: 'foo',
      }, {
        headers: {
          Authorization: `Bearer baz`,
        },
      },)
      .reply(201);

    const selectors = {
      getMsg: () => 'bar',
    };

    return expectSaga(postWallpost, selectors)
      .withReducer(reducers, initialState)
      .put(postSucceeded)
      .run();

  });
});
```

SAGA:
```Javascript
const getMsg = state => state.wallpost.msg;

export function* postWallpost() {
  const msg = yield select(getMsg);
  const token = yield call(loadToken);
  const { response } = yield call(axios.post,
    `${config.API_BASE_URL}/posts/post`,
    {
      msg,
    }, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    },
  );

  if (response) {
    yield call(Alert.success, 'Posted!');
    yield put(postSucceeded());
  } else {
    yield call(Alert.error, 'Opps... Connection error 1. :/');
    yield put(postFailed(ERR_POST_GENERIC));
  }
}

export function* watchWallPostForm() {
  yield* takeEvery(POST_REQUESTED, postWallpost);
}

```

**Comment by jfairbank** [comment]
Hi @mpmlj!

Initially looking at your code, you seem to be using `expectSaga` correctly. I did notice that you're using `config.API_BASE_URL` for your URL in your saga, but mocking out localhost in your tests. Is `API_BASE_URL` an absolute URL that includes the http protocol and domain name, i.e. http://some-url.com? If so, then that may be your issue. nock might not be seeing the http request.

If it's not that, then `expectSaga` might be timing out. Can you try increasing the timeout or turning it off altogether? There's more info in the docs: [timeout](http://redux-saga-test-plan.jeremyfairbank.com/integration-testing/timeout.html), but you can pass in the timeout as a number in milliseconds or pass in `false` into the `run` method. Note: your testing framework might still time out even if you pass in `false` to `run`.

```js
// time out after 500 ms
return expectSaga(postWallpost, selectors)
  .withReducer(reducers, initialState)
  .put(postSucceeded)
  .run(500);

// don't time out. wait for saga to complete.
return expectSaga(postWallpost, selectors)
  .withReducer(reducers, initialState)
  .put(postSucceeded)
  .run(false);
```

If you're still having trouble after those suggestions, would you be able to reproduce the problem in a repo that I can look at?

Thanks!

**Comment by mpmlj** [comment]
@jfairbank 

config.API_BASE_URL is correct, turned out - its axios could not be easily (or at all?) setup to work with nock in saga tests. Switching to fetch library resolved that. That, and also, I had to start testing saga-worker directly, not via saga-watcher.

So I have a question regarding this - what is the correct approach to test a combination of watcher with a worker using redux-saga-test-plan?

I tried testing them separately: https://gist.github.com/mpmlj/303e5e5432e06ba499fae27068b2744b
No success here, throws "...takeLatest did not take a pattern..."

And also I tried testing both as a single whole, thinking i will be "re-routed" from the watcher into the worker saga and with the help of expectSaga I won't need to care about takeLatest - but no luck as well.

Here's a working gist, though: https://gist.github.com/mpmlj/302a4f2ac31535c6a64bbf2ef347dede
As you can see, it just tests the worker saga directly.

If you have any suggestions - that would be great!
Trying to figure out how to takeLatest into account.

Also, if, by chance, you made your helper working with axios - I would appreciate any advice on that :)

Best,
D.

**Comment by jfairbank** [comment]
@mpmlj This is an old issue that I totally lost track of. So sorry about that! Do you still need any help?

**Comment by jfairbank** [comment]
Closing this for now. Please reopen if you're still having issues.
