### ISSUE TITLE
Docs page not responding

### ISSUE THREAD

**Issue by nbotalov** [jfairbank/redux-saga-test-plan#63]
Hi,
http://redux-saga-test-plan.jeremyfairbank.com/ not responding

**Comment by jfairbank** [comment]
Thanks for notifying me! I let the domain name temporarily expire 🙃 .

Hopefully, the docs will be back up soon.

**Comment by nbotalov** [comment]
Thanks for great library and documentation)

**Comment by jfairbank** [comment]
Opening this back up. Having an issue with Clouflare banning the subdomain on my domain name.

You can access the docs at http://jfairbank.github.io/redux-saga-test-plan/ for now.

**Comment by jfairbank** [comment]
Everything back to normal. Thanks again for alerting me!

Docs are available again [redux-saga-test-plan.jeremyfairbank.com](http://redux-saga-test-plan.jeremyfairbank.com).
