### ISSUE TITLE
take with multiple actions seems not to work

### ISSUE THREAD

**Issue by koellcode** [jfairbank/redux-saga-test-plan#76]
Hey! I'm using redux-saga-test-plan and I really enjoy it!

But currently I'm a bit stucked, I use expectSaga and to test code like this:

const takenAction = yield take([ACTION1, ACTION2]);
console.log('hello');

when I try to dispatch one of both actions

expectSaga(rootSaga)
.dispatch(ACTION1)
.run({ silenceTimeout: true });

I would expect to see the 'hello' because one of two matches. But somehow this does not work. It works when I do const takenAction = yield take(ACTION1).

At runtime in the Browser it seems to work as expected.

maybe I hold it wrong? :)

btw. nice utilities!

**Comment by koellcode** [comment]
ok it seems to work with

const { Action1, Action2 } = yield race({
      Action1: take(ACTION1),
      Action2: take(ACTION2),
    });
console.log('hello');

obviously i hold it wrong

**Comment by jfairbank** [comment]
Hi, @koellcode!

This is definitely a bug, so thanks for finding it. I need to update how to handle patterns that aren't strings (e.g. arrays or functions):
https://redux-saga.github.io/redux-saga/docs/api/index.html#takepattern.

You _can_ use a `race` here, but the better approach would be to yield `take` with an array. I'll work on a bug fix.

**Comment by jfairbank** [comment]
I released a bug fix in v2.3.1 @koellcode. If it doesn't work, please let me know. Thanks!
