### ISSUE TITLE
Allow multiple providers

### ISSUE THREAD

**Issue by jfairbank** [jfairbank/redux-saga-test-plan#88]
It would be nice to pass in multiple providers via an array argument to `.provide()`. This would be similar to middleware like Redux has. This would also allow providers to be more reusable.

**Comment by jfairbank** [comment]
Added in v2.4.0!

**Comment by cefn** [comment]
Is there a reason why not just allow multiple arguments - especially with widespread ...spread support. I can't find another role for the second argument right now...

https://github.com/jfairbank/redux-saga-test-plan/blob/master/src/expectSaga/index.js#L696

Using indefinitely-many arguments as the default API signature makes it less likely that you will have silent failures from missing outer array brackets, which cause subsequent arguments to be thrown into the void.
