### ISSUE TITLE
Make depth property configurable (serializeEffect.js)

### ISSUE THREAD

**Issue by aalbul** [jfairbank/redux-saga-test-plan#95]
Hi, writing this issue because spent almost an hour (again) trying to understand why 2 effects does not match. The contained JSON structure with tree that contained a lot of children. Just because serializeEffect.js passes "depth: 3" to util-inspect.inspect, i was not able to see the difference inside of children.

My output looked like this: 

`    SagaTestError:
    Assertion 2 failed: put effects do not match

    Expected
    --------
    { channel: null,
      action:
       { id: '123',
         items:
          [ { children: [Object],
              className: 'compare',
              label: 'Compare',
              menuIcon: undefined,
              type: 'SUBMENU' },
            { action: 'RENAME_CI',
              ciType: undefined,
              className: 'rename',
              label: 'Rename',
              menuIcon: undefined,
              type: 'ACTION' },
            { action: 'DUPLICATE_CI',
              ciType: undefined,
              className: 'duplicate',
              label: 'Duplicate',
              menuIcon: undefined,
              type: 'ACTION' },
            { type: 'DIVIDER' },
            { action: 'DELETE_CI',
              ciType: undefined,
              className: 'delete',
              label: 'Delete',
              menuIcon: undefined,
              type: 'ACTION' } ],
         target: '',
         type: 'SHOW_CONTEXT_MENU' } }

    Actual
    ------
    { channel: null,
      action:
       { id: '123',
         items:
          [ { children: [Object],
              className: 'compare',
              label: 'Compare',
              menuIcon: undefined,
              type: 'SUBMENU' },
            { action: 'RENAME_CI',
              ciType: undefined,
              className: 'rename',
              label: 'Rename',
              menuIcon: undefined,
              type: 'ACTION' },
            { action: 'DUPLICATE_CI',
              ciType: undefined,
              className: 'duplicate',
              label: 'Duplicate',
              menuIcon: undefined,
              type: 'ACTION' },
            { type: 'DIVIDER' },
            { action: 'DELETE_CI',
              ciType: undefined,
              className: 'delete',
              label: 'Delete',
              menuIcon: undefined,
              type: 'ACTION' } ],
         target: '',
         type: 'SHOW_CONTEXT_MENU' } }`

The problem was simple: first children of first element didn't have an expected field.
I aware that i can use not exact match. But i'm still wondering if it's possible to have some configuration for particular saga or whole project.

What about .redux-saga-test-plan config file in project or something like this? Do you have any plans or opinion on this? :)

**Comment by jfairbank** [comment]
Hi, @aalbul!

Thanks for the suggestion. I was actually thinking of making an issue for this as well. I've run into an opposite problem where the depth was too much and creating a lot of noise in my error messages.

I'm not a fan of adding a dotfile for this, so I'll work on adding a method to the API as well as probably supporting a default option property on the `testSaga` function.

**Comment by davidpene** [comment]
Hi @aalbul I've run into the same problem, when unit testing. 

Did you manage to get around this, without the upcoming change?

Cheers

**Comment by danielbartsch** [comment]
Hello!

My team and me frequently run into this issue, where there's seemingly no difference between expected and actual.
The only way to investigate further, is to go to `node_modules/redux-saga-test-plan/lib/expectSaga/expectations.js` and change every occurrence of `depth: 3`, which is really not that convenient.

Is there no better way change the depth of this module for a test run?

Thanks!

**Comment by rolandas-valantinas** [comment]
I'm sure it shouldn't take 3 years to make one property configurable  :see_no_evil:

**Comment by jp928** [comment]
https://github.com/jfairbank/redux-saga-test-plan/pull/366 should solve this issue. Many thanks to @AdeonMaster
